# Generated by Django 3.0.7 on 2020-06-10 09:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('has_extra_toppings', models.IntegerField(default=0)),
                ('priceSmall', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('priceLarge', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('order_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('user_id', models.CharField(max_length=64)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='orders.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizeName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('itemtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppingtype', to='orders.ItemType')),
            ],
        ),
        migrations.CreateModel(
            name='TmpOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('order_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('order_id', models.CharField(default='23672', max_length=64)),
                ('orderitem', models.ManyToManyField(blank=True, related_name='items', to='orders.OrderItem')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='itemSize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='orders.Size'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.TmpOrder'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Toppings'),
        ),
        migrations.AddField(
            model_name='item',
            name='itemtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemtype', to='orders.ItemType'),
        ),
    ]
