# Generated by Django 3.0.7 on 2020-06-05 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_toppings', models.BooleanField(default=False)),
                ('itemPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('itemSize', models.CharField(max_length=64)),
                ('user_id', models.IntegerField(default=None)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='orders.Item')),
            ],
        ),
    ]
