# Generated by Django 3.0.7 on 2020-06-07 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200607_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('itemtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppingtype', to='orders.ItemType')),
            ],
        ),
    ]
