# Generated by Django 3.0.7 on 2020-06-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_toppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='has_toppings',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Toppings'),
        ),
    ]
