# Generated by Django 3.0.7 on 2020-06-08 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200608_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None)),
                ('order_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('order_id', models.CharField(default='84682', max_length=64)),
            ],
        ),
    ]
