# Generated by Django 3.0.7 on 2020-06-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_tmporder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmporder',
            name='order_id',
            field=models.CharField(default='14206', max_length=64),
        ),
    ]
